export enum ROUTES {
    HOME = '/',
    LOGIN = '/login-form',
    REGISTER = '/register-form',
    USER_HOME = '/user',
    USER_PROFILE = '/user/profile',
    USER_MESSAGES = '/user/messages',
    USER_ACCOUNT = '/user/account',
    USER_OFFERS = '/user/my-offers',
    USER_INQUIRIES = '/user/inquiries',
    USER_LOANS = '/user/loans',
    USER_MAKE_INQUIRIES = '/user/inquiry-form',
    USER_MAKE_OFFER = '/user/offer-form',
    USER_FIND_INQUIRIES = '/user/find-inqueries',
}
