export enum ROUTES {
    HOME = '/',
    LOGIN = '/login-form',
    REGISTER = '/register-form',
    USER_HOME = '/user',
    USER_PROFILE = '/user/profile',
    USER_PROFILE_CHANGE_EMAIL = '/user/profile/change-email-form',
    USER_PROFILE_CHANGE_PASSWORD = '/user/profile/change-password-form',
    USER_PROFILE_DELETE_ACCOUNT = '/user/profile/delete-account',
    USER_MESSAGES = '/user/messages',
    USER_ACCOUNT = '/user/account',
    USER_OFFERS = '/user/my-offers',
    USER_INQUIRIES = '/user/inquiries',
    USER_LOANS = '/user/loans',
    USER_LOANS_PAID_OFF = '/user/loans/paid-off',
    USER_LOANS_PENDING = '/user/loans/pending',
    USER_MAKE_INQUIRIES = '/user/inquiry-form',
    USER_MAKE_OFFER = '/user/offer-form',
    USER_FIND_INQUIRIES = '/user/find-inqueries',
}
